import {
  BarChart3,
  Activity,
  ClipboardCheck,
  LayoutDashboard,
  Languages,
  Leaf,
  PackageSearch,
  Route,
  Truck,
  WalletCards,
  Warehouse,
} from "lucide-react";
import type { AdminNavItem, AdminShellConfig } from "@/features/admin/domain/types/admin.types";

const ecosystemTopTabs = [
  { href: "/admin", labelKey: "dashboard" },
  { href: "/admin/orders", labelKey: "orders" },
  { href: "/admin/warehouses", labelKey: "warehouses" },
] as const;

export const adminNavItems: ReadonlyArray<AdminNavItem> = [
  { href: "/admin", icon: LayoutDashboard, labelKey: "dashboard" },
  { href: "/admin/analytics", icon: BarChart3, labelKey: "analytics" },
  { href: "/admin/observability", icon: Activity, labelKey: "observability" },
  { href: "/admin/role-requests", icon: ClipboardCheck, labelKey: "roleRequests" },
  { href: "/admin/orders", icon: PackageSearch, labelKey: "orders" },
  { href: "/admin/trips", icon: Route, labelKey: "trips" },
  { href: "/admin/fleet", icon: Truck, labelKey: "fleet" },
  { href: "/admin/wallet", icon: WalletCards, labelKey: "wallet" },
  { href: "/admin/sustainability", icon: Leaf, labelKey: "sustainability" },
  { href: "/admin/warehouses", icon: Warehouse, labelKey: "warehouses" },
  { href: "/admin/language", icon: Languages, labelKey: "language" },
];

export const adminShellConfigByPath: Record<string, AdminShellConfig> = {
  "/admin": {
    initials: "SC",
    searchPlaceholderKey: "searchPlaceholderShipment",
    titleKey: "titleDashboard",
    topBarVariant: "dashboard",
    topTabs: ecosystemTopTabs,
  },
  "/admin/analytics": {
    initials: "SA",
    searchPlaceholderKey: "searchPlaceholderInsight",
    supportLabelKey: "supportLabel",
    titleKey: "titleAdmin",
    topBarVariant: "standard",
    topTabs: ecosystemTopTabs,
  },
  "/admin/fleet": {
    initials: "FO",
    searchPlaceholderKey: "searchPlaceholderFleet",
    supportLabelKey: "supportLabel",
    titleKey: "titleAdmin",
    topBarVariant: "standard",
    topTabs: ecosystemTopTabs,
  },
  "/admin/observability": {
    initials: "OBS",
    searchPlaceholderKey: "searchPlaceholderObservability",
    supportLabelKey: "supportLabel",
    titleKey: "titleAdmin",
    topBarVariant: "standard",
    topTabs: ecosystemTopTabs,
  },
  "/admin/wallet": {
    initials: "COD",
    searchPlaceholderKey: "searchPlaceholderWallet",
    supportLabelKey: "supportLabel",
    titleKey: "titleAdmin",
    topBarVariant: "standard",
    topTabs: ecosystemTopTabs,
  },
  "/admin/orders": {
    initials: "SM",
    searchPlaceholderKey: "searchPlaceholderOrders",
    titleKey: "titleCenter",
    topBarVariant: "ecosystem",
    topTabs: ecosystemTopTabs,
  },
  "/admin/trips": {
    initials: "TR",
    searchPlaceholderKey: "searchPlaceholderTrips",
    supportLabelKey: "supportLabel",
    titleKey: "titleAdmin",
    topBarVariant: "standard",
    topTabs: ecosystemTopTabs,
  },
  "/admin/notifications": {
    initials: "NT",
    searchPlaceholderKey: "searchPlaceholderNotifications",
    supportLabelKey: "supportLabel",
    titleKey: "titleAdmin",
    topBarVariant: "standard",
    topTabs: ecosystemTopTabs,
  },
  "/admin/role-requests": {
    initials: "RR",
    searchPlaceholderKey: "searchPlaceholderRoleRequests",
    supportLabelKey: "supportLabel",
    titleKey: "titleAdmin",
    topBarVariant: "standard",
    topTabs: ecosystemTopTabs,
  },
  "/admin/sustainability": {
    initials: "SI",
    searchPlaceholderKey: "searchPlaceholderSustainability",
    titleKey: "titleAdmin",
    topBarVariant: "standard",
    topTabs: ecosystemTopTabs,
  },
  "/admin/warehouses": {
    initials: "IH",
    searchPlaceholderKey: "searchPlaceholderWarehouses",
    titleKey: "titleCenter",
    topBarVariant: "ecosystem",
    topTabs: ecosystemTopTabs,
  },
  "/admin/language": {
    initials: "LG",
    searchPlaceholderKey: "searchPlaceholderLanguage",
    supportLabelKey: "supportLabel",
    titleKey: "titleAdmin",
    topBarVariant: "standard",
    topTabs: ecosystemTopTabs,
  },
};
